// KT/kt1/src/components/TodoList.vue
<template>
    <div>
        <TodoItem
            v-for="el in todos"
            :key="el.id"
            :id="el.id"
            :title="el.title"
            :completed="el.completed"
            :deleteTodoByid="deleteTodoByid"
            :changeTodos="changeTodos"
        />
    </div>
</template>

<script>
import TodoItem from './TodoItem'
export default {
    components: {
        TodoItem,
    },
    name: 'TodoList',
    props: {
        todos: {
            type: Array,
            required: true,
        },
        deleteTodoByid: {
            type: Function,
            required: true,
        },
        changeTodos: {
            type: Function,
            required: true,
        },
    },
}
</script>

// ithub-3r1-main/React/ReactLess_3(TodoApp)/myapp/src/components/TodoList.jsx
import TodoItem from './TodoItem'

function TodoList(props) {
    const { todos, deleteTodoByid, changeTodos } = props
    return (
        <div>
            {todos.map(elem => (
                <TodoItem
                    key={elem.id}
                    id={elem.id}
                    title={elem.title}
                    completed={elem.completed}
                    deleteTodoByid={deleteTodoByid}
                    changeTodos={changeTodos}
                />
            ))}
        </div>
    )
}

export default TodoList
