// ithub-3r1-main/Angular/AngularLess_4(routing, httpModule)/myapp/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

interface MenuItem {
  id: number
  path: string
  title: string
}

@Component({
  selector: 'app-header',
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  public menuList: MenuItem[] = [
    {id: 1, title: 'Home', path: '/home'},
    {id: 2, title: 'About', path: '/about'},
    {id: 3, title: 'Contacts', path: '/contacts'},
  ]
}

<style>
    header {
        padding: 40px 20px;
        background-color: antiquewhite;

        display: flex;
        align-items: center;
        justify-content: space-around;
    }
    .logo{
        width: 40px;
        height: 40px;

        border-radius: 50% ;
        background-color: brown;
    }
    .menu_wrapper{
        list-style-type: none;
        display: flex;
        align-items: center;
        gap: 10px;
        font-size: 25px;
    }

    a {
        text-decoration: none;
        color: black;
    }

    a.active {
        color: purple;
        text-decoration: underline 
    }
</style>

<header>
    <div class="logo"></div>
    <ul class="menu_wrapper">
        @for(elem of menuList; track elem.id){
            <li>
                <a [routerLink]="elem.path" routerLinkActive="active">{{elem.title}}</a>
                <!-- <a routerLink="/page/link" > Page component ...</a> -->
            </li>
        }
    </ul>
</header>

// KT/kt2/src/components/Header.vue
<template>
    <header class="header">
        <nav class="menu">
            <RouterLink to="/"><li>Home</li></RouterLink>
            <RouterLink to="/about"><li>About</li></RouterLink>
            <RouterLink to="/contacts"><li>Contacts</li></RouterLink>
        </nav>
    </header>
</template>

<script>
import { RouterLink } from 'vue-router'

export default {}
</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=Heebo:wght@400;700&display=swap');
.header {
    font-family: 'Heebo', sans-serif;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 1000;
    display: flex;
    align-items: center;
    justify-content: right;
    padding-top: 20px;
}

.menu {
    font-family: 'Heebo', sans-serif;
    display: flex;
    gap: 30px;
    list-style: none;
    font-size: 30px;
    padding-right: 117px;
}
.menu a {
    text-decoration: none;
    color: black;
}
</style>
