// ithub-3r1-main/React/ReactLess_3(TodoApp)/myapp/src/App.js
import { useEffect, useState } from 'react'
import AddForm from './components/AddForm'
import TodoList from './components/TodoList'

function App() {
    const start_todos = [
        { id: 1, title: 'Помыть руки', completed: true },
        { id: 2, title: 'Сделать зарядку', completed: false },
        { id: 3, title: 'Наконец изучить React', completed: true },
    ]

    let local_data = JSON.parse(localStorage.getItem('todos'))

    const [todos, setTodos] = useState(local_data || start_todos)

    function deleteTodoByid(id) {
        let filteredTodos = todos.filter(elem => elem.id !== id)
        setTodos(filteredTodos)
    }

    function changeTodos(id) {
        let newTodos = todos.map(todo => {
            if (todo.id === id) {
                todo.completed = !todo.completed
            }
            return todo
        })
        setTodos(newTodos)
    }

    function addTodo(title) {
        let newTodo = {
            id: Date.now(),
            title,
            completed: false,
        }
        setTodos([...todos, newTodo])
    }
    useEffect(() => {
        localStorage.setItem('todos', JSON.stringify(todos))
    }, [todos])

    return (
        <div>
            <AddForm addTodo={addTodo} />
            <TodoList
                todos={todos}
                changeTodos={changeTodos}
                deleteTodoByid={deleteTodoByid}
            />
        </div>
    )
}

export default App

// KT/kt1/src/App.vue
<template>
    <AddForm :addTodo="addTodo" />
    <TodoList
        :todos="todos"
        :changeTodos="changeTodos"
        :deleteTodoByid="deleteTodoByid"
    />
</template>

<script>
import AddForm from './components/AddForm.vue'
import TodoList from './components/TodoList.vue'

export default {
    name: 'App',
    components: {
        AddForm,
        TodoList,
    },
    data() {
        return {
            start_todos: [
                { id: 1, title: 'Помыть руки', completed: true },
                { id: 2, title: 'Сделать зарядку', completed: false },
                { id: 3, title: 'Наконец изучить React', completed: true },
            ],
            todos: [],
        }
    },
    created() {
        const LocalData = JSON.parse(localStorage.getItem('todos'))
        if (!Array.isArray(LocalData) || LocalData.length === 0) {
            this.todos = [...this.start_todos]
        } else {
            this.todos = LocalData
        }
    },
    methods: {
        addTodo(title) {
            const newTodo = {
                id: Date.now(),
                title,
                completed: false,
            }
            this.todos = [...this.todos, newTodo]
            this.saveTodos()
        },
        deleteTodoByid(id) {
            this.todos = this.todos.filter(elem => elem.id !== id)
            this.saveTodos()
        },
        changeTodos(id) {
            this.todos = this.todos.map(todo => {
                if (todo.id === id) {
                    return { ...todo, completed: !todo.completed }
                }
                return todo
            })
            this.saveTodos()
        },
        saveTodos() {
            localStorage.setItem('todos', JSON.stringify(this.todos))
        }
    },
}
</script>

<style>
#app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
}
</style>
